# Generated by Django 4.2.30 on 2026-05-14 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        ('locations', '0002_rename_loaction_location'),

    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=255)),
                ('product_ref_number', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['product_name'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('supplier_id', models.AutoField(primary_key=True, serialize=False)),
                ('supplier_name', models.CharField(max_length=255)),
                ('contact_name', models.CharField(max_length=255)),
                ('contact_email', models.EmailField(max_length=255)),
            ],
            options={
                'ordering': ['supplier_name'],
            },
        ),
        migrations.CreateModel(
            name='ProductSupplier',
            fields=[
                ('product_supplier_id', models.AutoField(primary_key=True, serialize=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_suppliers', to='inventory.product')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_suppliers', to='inventory.supplier')),
            ],
            options={
                'verbose_name': 'Product Supplier',
                'verbose_name_plural': 'Product Suppliers',
                'unique_together': {('product', 'supplier')},
            },
        ),
        migrations.AddField(
            model_name='product',
            name='suppliers',
            field=models.ManyToManyField(related_name='products', through='inventory.ProductSupplier', to='inventory.supplier'),
        ),
        migrations.CreateModel(
            name='InventoryReceipt',
            fields=[
                ('receipt_id', models.AutoField(primary_key=True, serialize=False)),
                ('lot_number', models.CharField(max_length=100)),
                ('receiving_condition', models.CharField(choices=[('Frozen', 'Frozen'), ('On Ice', 'On Ice'), ('Room-Temperature', 'Room-Temperature')], default='Room-Temperature', max_length=50)),
                ('date_received', models.DateField()),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('received_by', models.CharField(max_length=255)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='inventory.product')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='inventory.supplier')),
            ],
            options={
                'verbose_name': 'Inventory Receipt',
                'verbose_name_plural': 'Inventory Receipts',
                'ordering': ['-date_received'],
            },
        ),
        migrations.CreateModel(
            name='TempLog',
            fields=[
                ('temp_log_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_logged', models.DateField()),
                ('current_temp_c', models.DecimalField(decimal_places=2, max_digits=5)),
                ('max_temp_c', models.DecimalField(decimal_places=2, max_digits=5)),
                ('min_temp_c', models.DecimalField(decimal_places=2, max_digits=5)),
                ('max_humidity', models.DecimalField(blank=True, decimal_places=2, help_text='Room locations only.', max_digits=5, null=True)),
                ('min_humidity', models.DecimalField(blank=True, decimal_places=2, help_text='Room locations only.', max_digits=5, null=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='templogs', to='locations.location')),
            ],
            options={
                'verbose_name': 'Temperature Log',
                'verbose_name_plural': 'Temperature Logs',
                'ordering': ['-date_logged'],
                'unique_together': {('location', 'date_logged')},
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('inventory_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity_on_hand', models.IntegerField(default=0)),
                ('last_updated', models.DateField(auto_now=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_entries', to='locations.location')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_entries', to='inventory.product')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_entries', to='inventory.inventoryreceipt')),
            ],
            options={
                'verbose_name': 'Inventory',
                'verbose_name_plural': 'Inventory',
                'unique_together': {('product', 'location', 'receipt')},
            },
        ),
    ]
