# Generated by Django 4.2.30 on 2026-05-20 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TempLog',
        ),
    ]
