# Generated by Django 4.2.30 on 2026-05-25 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_delete_templog'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryreceipt',
            name='receipt_notes',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_notes',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
