# Generated by Django 4.2.30 on 2026-05-25 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_inventoryreceipt_receipt_notes_product_product_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryreceipt',
            name='quantity_received',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inventoryreceipt',
            name='quantity_unit',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
