# Generated by Django 4.2.30 on 2026-05-25 14:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0004_inventoryreceipt_quantity_received_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryreceipt',
            name='received_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_receipts_received', to=settings.AUTH_USER_MODEL),
        ),
    ]
