# Generated by Django 4.2.30 on 2026-05-25 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0005_alter_templog_date_logged'),
        ('inventory', '0005_alter_inventoryreceipt_received_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryreceipt',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_receipts', to='locations.location'),
            preserve_default=False,
        ),
    ]
