# Generated by Django 4.2.30 on 2026-05-25 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_inventoryreceipt_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='quantity_unit',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
