# Generated by Django 4.2.30 on 2026-06-23 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_inventory_quantity_unit'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='inventoryreceipt',
            unique_together={('product', 'lot_number')},
        ),
    ]
