from django import forms
from locations.models import Location
from .models import Sample,Project,Case,SpecimenType,Client

class BulkLocationForm(forms.Form):
    location = forms.ModelChoiceField(
        queryset=Location.objects.all(),
        required=True
    )

class BulkReceivingConditionForm(forms.Form):
    receiving_condition = forms.ChoiceField(
        choices=Sample.RECEIVING_CONDITION_CHOICES,
        required=True
    )


class SampleAddForm(forms.Form):
    """
    Form for adding a single sample from the frontend.
    The sample_name is auto-generated by the model 
    """

    project = forms.ModelChoiceField(
        queryset=Project.objects.order_by('project_name'),
        required=True,
        empty_label='— Select project —',
        widget=forms.Select(attrs={
            'class': 'form-select form-select-lims',
            'id':    'id_project',
        })
    )

    case = forms.ModelChoiceField(
        queryset=Case.objects.none(),    # populated dynamically via JS/view
        required=True,
        empty_label='— Select project first —',
        widget=forms.Select(attrs={
            'class': 'form-select form-select-lims',
            'id':    'id_case',
        })
    )

    specimen_type = forms.ModelChoiceField(
        queryset=SpecimenType.objects.order_by('specimen_type'),
        required=True,
        empty_label='— Select specimen type —',
        widget=forms.Select(attrs={
            'class': 'form-select form-select-lims',
            'id':    'id_specimen_type',
        })
    )

    sample_type = forms.ChoiceField(
        choices=[('', '— Select type —'), ('DNA', 'DNA'), ('RNA', 'RNA')],
        required=True,
        widget=forms.Select(attrs={
            'class': 'form-select form-select-lims',
            'id':    'id_sample_type',
        })
    )

    receiving_condition = forms.ChoiceField(
        choices=[('', '— Select condition —')] + list(Sample.RECEIVING_CONDITION_CHOICES),
        required=False,
        widget=forms.Select(attrs={
            'class': 'form-select form-select-lims',
        })
    )

    location = forms.ModelChoiceField(
        queryset=Location.objects.order_by('storageType', 'locationName'),
        required=False,
        empty_label='— Select location (optional) —',
        widget=forms.Select(attrs={
            'class': 'form-select form-select-lims',
        })
    )

    volume_received = forms.FloatField(
        required=False,
        widget=forms.NumberInput(attrs={
            'class':       'form-control form-control-lims',
            'placeholder': '-',
            'step':        '0.1',
            'min':         '0',
        })
    )

    concentration = forms.FloatField(
        required=False,
        widget=forms.NumberInput(attrs={
            'class':       'form-control form-control-lims',
            'placeholder': '-',
            'step':        '0.01',
            'min':         '0',
        })
    )

    notes = forms.CharField(
        required=False,
        max_length=255,
        widget=forms.TextInput(attrs={
            'class':       'form-control form-control-lims',
            'placeholder': 'Optional notes…',
        })
    )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        
        if 'project' in self.data:
            try:
                project_id = int(self.data.get('project'))
                project    = Project.objects.get(pk=project_id)
                self.fields['case'].queryset = Case.objects.filter(
                    client=project.client
                ).order_by('case_name')
                self.fields['case'].empty_label = '— Select case —'
            except (ValueError, Project.DoesNotExist):
                pass

class ClientForm(forms.ModelForm):
    class Meta:
        model  = Client
        fields = ["client_name", "organisation_name"]
        widgets = {
            "client_name": forms.TextInput(attrs={
                "class":       "form-control form-control-lims",
                "placeholder": "Dr. Jane Smith...",
            }),
            "organisation_name": forms.TextInput(attrs={
                "class":       "form-control form-control-lims",
                "placeholder": "Atlantic Cancer Research Institute...",
            }),
        }


class ProjectForm(forms.ModelForm):

    SEQUENCING_CHOICES = [
        ("Long", "Long"),
        ("Short", "Short"),
        ("WGS", "WGS"),
        ("CUSTOM", "Custom"),
    ]

    sequencing_choice = forms.ChoiceField(
        choices=SEQUENCING_CHOICES,
        widget=forms.Select(attrs={
            "class": "form-select form-select-lims",
            "id":    "id_sequencing_choice",
        }),
    )

    custom_sequencing = forms.CharField(
        required=False,
        widget=forms.TextInput(attrs={
            "class":       "form-control form-control-lims",
            "placeholder": "Describe the sequencing type…",
            "id":          "id_custom_sequencing",
        }),
    )
    def save(self, commit=True):
        project = super().save(commit=False)

        seq = self.cleaned_data["sequencing_choice"]

        if seq == "CUSTOM":
            project.sequencing_type = self.cleaned_data["custom_sequencing"]
        else:
            project.sequencing_type = seq

        if commit:
            project.save()

        return project
    class Meta:
        model  = Project
        fields = ["project_name", "client", "sequencing_choice", "custom_sequencing"]
        widgets = {
            "project_name": forms.TextInput(attrs={
                "class":       "form-control form-control-lims",
                "placeholder": "LungCancer...",
                "id":          "id_project_name",
            }),
            "client": forms.Select(attrs={
                "class": "form-select form-select-lims",
                "id":    "id_client",
            }),
        }