# Generated by Django 4.2.30 on 2026-05-13 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('samples', '0002_remove_sample_location_id_sample_sample_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Batch Sample',
                'verbose_name_plural': 'Batch Samples',
            },
        ),
        migrations.CreateModel(
            name='SampleQCBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_name', models.CharField(max_length=255)),
                ('date_batched', models.DateField()),
                ('created_by', models.CharField(max_length=255)),
                ('samples', models.ManyToManyField(related_name='qc_batches', through='qc.BatchSample', to='samples.sample')),
            ],
            options={
                'verbose_name': 'Sample QC Batch',
                'verbose_name_plural': 'Sample QC Batches',
                'ordering': ['-date_batched'],
            },
        ),
        migrations.CreateModel(
            name='SampleQC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qubit_nm', models.FloatField(blank=True, null=True)),
                ('rin', models.FloatField(blank=True, null=True)),
                ('dv200', models.FloatField(blank=True, null=True)),
                ('nanodrop_260_280', models.FloatField(blank=True, null=True)),
                ('nanodrop_260_230', models.FloatField(blank=True, null=True)),
                ('qc_status', models.CharField(choices=[('Pass', 'Pass'), ('Fail', 'Fail'), ('Caution', 'Caution'), ('Pending', 'Pending')], default='Pending', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='qc_results', to='qc.sampleqcbatch')),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='qc_results', to='samples.sample')),
            ],
        ),
        migrations.AddField(
            model_name='batchsample',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_samples', to='qc.sampleqcbatch'),
        ),
        migrations.AddField(
            model_name='batchsample',
            name='sample',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batch_memberships', to='samples.sample'),
        ),
        migrations.AlterUniqueTogether(
            name='batchsample',
            unique_together={('batch', 'sample')},
        ),
    ]
