# Generated by Django 4.2.30 on 2026-05-14 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qc', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sampleqc',
            name='nanodrop_260_280',
        ),
    ]
