# Generated by Django 4.2.30 on 2026-05-21 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qc', '0002_remove_sampleqc_nanodrop_260_280'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sampleqcbatch',
            name='batch_name',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
    ]
