# Generated by Django 4.2.30 on 2026-05-25 14:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('qc', '0003_alter_sampleqcbatch_batch_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sampleqcbatch',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='qc_batches_created', to=settings.AUTH_USER_MODEL),
        ),
    ]
