# Generated by Django 4.2.30 on 2026-05-26 17:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('qc', '0005_sampleqc_nanodrop_260_280'),
    ]

    operations = [
        migrations.AddField(
            model_name='sampleqc',
            name='edited_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='sample_qc_edited', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
