# Generated by Django 4.2.30 on 2026-06-10 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0014_userprofile'),
        ('qc', '0006_sampleqc_edited_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='sampleqcbatch',
            name='batch_type',
            field=models.CharField(choices=[('DNA', 'DNA'), ('RNA', 'RNA')], default='RNA', max_length=10),
        ),
        migrations.AddField(
            model_name='sampleqcbatch',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='qc_batches', to='samples.project'),
        ),
    ]
