# Generated by Django 4.2.30 on 2026-06-11 12:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0014_userprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('qc', '0007_sampleqcbatch_batch_type_sampleqcbatch_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('save', 'Board saved'), ('create', 'Batch created'), ('delete', 'Batch deleted')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('diff_json', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True, default='')),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='qc.sampleqcbatch')),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batch_audit_logs', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batch_audit_logs', to='samples.project')),
            ],
            options={
                'verbose_name': 'Batch Audit Log',
                'verbose_name_plural': 'Batch Audit Logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
