# Generated by Django 4.2.30 on 2026-07-14 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qc', '0008_batchauditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='sampleqcbatch',
            name='gate_dna_260_230_caution_min',
            field=models.FloatField(default=1.4, verbose_name='DNA: Nanodrop 260/230 Caution Minimum'),
        ),
        migrations.AddField(
            model_name='sampleqcbatch',
            name='gate_dna_260_230_pass_min',
            field=models.FloatField(default=1.7, verbose_name='DNA: Nanodrop 260/230 Pass Minimum'),
        ),
        migrations.AddField(
            model_name='sampleqcbatch',
            name='gate_dna_260_280_min',
            field=models.FloatField(default=1.79, verbose_name='DNA: Nanodrop 260/280 Minimum'),
        ),
        migrations.AddField(
            model_name='sampleqcbatch',
            name='gate_dna_elution_ul',
            field=models.FloatField(default=100.0, verbose_name='DNA: Elution Volume (µL)'),
        ),
        migrations.AddField(
            model_name='sampleqcbatch',
            name='gate_dna_min_ng',
            field=models.FloatField(default=100.0, help_text='Total ng required to pass the quantity gate (qubit_nm × elution volume).', verbose_name='DNA: Minimum Quantity (ng)'),
        ),
        migrations.AddField(
            model_name='sampleqcbatch',
            name='gate_rna_caution_dv200_max',
            field=models.FloatField(default=54.0, verbose_name='RNA: Caution Zone — dv200 Maximum'),
        ),
        migrations.AddField(
            model_name='sampleqcbatch',
            name='gate_rna_caution_dv200_min',
            field=models.FloatField(default=40.0, verbose_name='RNA: Caution Zone — dv200 Minimum'),
        ),
        migrations.AddField(
            model_name='sampleqcbatch',
            name='gate_rna_caution_rin_min',
            field=models.FloatField(default=1.99, verbose_name='RNA: Caution Zone — RIN Minimum'),
        ),
        migrations.AddField(
            model_name='sampleqcbatch',
            name='gate_rna_dv200_or_min',
            field=models.FloatField(default=55.0, verbose_name='RNA: dv200 Threshold, combined with RIN (row 2)'),
        ),
        migrations.AddField(
            model_name='sampleqcbatch',
            name='gate_rna_dv200_pass',
            field=models.FloatField(default=62.0, verbose_name='RNA: dv200 Pass Threshold, alone (row 3)'),
        ),
        migrations.AddField(
            model_name='sampleqcbatch',
            name='gate_rna_elution_ul',
            field=models.FloatField(default=40.0, help_text='Used to convert Qubit ng/µL into total ng: qubit_nm × this value.', verbose_name='RNA: Elution Volume (µL)'),
        ),
        migrations.AddField(
            model_name='sampleqcbatch',
            name='gate_rna_min_ng',
            field=models.FloatField(default=100.0, help_text='Total ng required to pass the quantity gate (qubit_nm × elution volume).', verbose_name='RNA: Minimum Quantity (ng)'),
        ),
        migrations.AddField(
            model_name='sampleqcbatch',
            name='gate_rna_rin_or_min',
            field=models.FloatField(default=2.0, verbose_name='RNA: RIN Threshold, combined with dv200 (row 2)'),
        ),
        migrations.AddField(
            model_name='sampleqcbatch',
            name='gate_rna_rin_pass',
            field=models.FloatField(default=5.0, help_text='RIN alone passes quality above this value.', verbose_name='RNA: RIN Pass Threshold (row 1)'),
        ),
    ]
