# Generated by Django 4.2.30 on 2026-07-23 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qc', '0009_sampleqcbatch_gate_dna_260_230_caution_min_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QCGatePreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('sample_type', models.CharField(choices=[('DNA', 'DNA'), ('RNA', 'RNA')], max_length=10)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('gate_rna_min_ng', models.FloatField(blank=True, null=True)),
                ('gate_rna_elution_ul', models.FloatField(blank=True, null=True)),
                ('gate_rna_rin_pass', models.FloatField(blank=True, null=True)),
                ('gate_rna_rin_or_min', models.FloatField(blank=True, null=True)),
                ('gate_rna_dv200_or_min', models.FloatField(blank=True, null=True)),
                ('gate_rna_dv200_pass', models.FloatField(blank=True, null=True)),
                ('gate_rna_caution_rin_min', models.FloatField(blank=True, null=True)),
                ('gate_rna_caution_dv200_min', models.FloatField(blank=True, null=True)),
                ('gate_rna_caution_dv200_max', models.FloatField(blank=True, null=True)),
                ('gate_dna_min_ng', models.FloatField(blank=True, null=True)),
                ('gate_dna_elution_ul', models.FloatField(blank=True, null=True)),
                ('gate_dna_260_280_min', models.FloatField(blank=True, null=True)),
                ('gate_dna_260_280_max', models.FloatField(blank=True, null=True)),
                ('gate_dna_260_230_pass_min', models.FloatField(blank=True, null=True)),
                ('gate_dna_260_230_caution_min', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'QC Gate Preset',
                'verbose_name_plural': 'QC Gate Presets',
                'ordering': ['sample_type', 'order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='sampleqcbatch',
            name='gate_dna_260_280_max',
            field=models.FloatField(blank=True, help_text='Leave blank for no upper bound. Some workflows (e.g. DNA PCR-Free) require 260/280 to stay under a ceiling, not just above a floor.', null=True, verbose_name='DNA: Nanodrop 260/280 Maximum (optional)'),
        ),
        migrations.AlterField(
            model_name='sampleqcbatch',
            name='gate_rna_caution_dv200_max',
            field=models.FloatField(default=54.0, verbose_name='RNA: Caution Zone: dv200 Maximum'),
        ),
        migrations.AlterField(
            model_name='sampleqcbatch',
            name='gate_rna_caution_dv200_min',
            field=models.FloatField(default=40.0, verbose_name='RNA: Caution Zone: dv200 Minimum'),
        ),
        migrations.AlterField(
            model_name='sampleqcbatch',
            name='gate_rna_caution_rin_min',
            field=models.FloatField(default=1.99, verbose_name='RNA: Caution Zone: RIN Minimum'),
        ),
    ]
