# Generated by Django 4.2.30 on 2026-05-13 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Loaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storageType', models.CharField(choices=[('Room-Temperature', 'Room-Temperature'), ('Fridge(4C)', 'Fridge(4C)'), ('Freezer(-20C)', 'Freezer(-20C)'), ('Freezer(-80C)', 'Freezer(-80C)')], max_length=255)),
                ('locationName', models.CharField(choices=[('Vanishing Cabinet', 'Vanishing Cabinet'), ('Netflix N Chill', 'Netflix N Chill'), ('James Bond', 'James Bond'), ('Yeti', 'Yeti'), ('Pre-PCR Room', 'Pre-PCR Room'), ('Post-PCR Room', 'Post-PCR Room'), ('4th floor -80C Freezer', '4th floor -80C Freezer'), ('4th floor -20C Freezer', '4th floor -20C Freezer')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Temp_Logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateLogged', models.DateTimeField(auto_now_add=True)),
                ('currentTempC', models.DecimalField(decimal_places=1, max_digits=2)),
                ('maxTempC', models.DecimalField(decimal_places=1, max_digits=2)),
                ('minTempC', models.DecimalField(decimal_places=1, max_digits=2)),
                ('maxHumidity', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('minHumidity', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='locations.loaction')),
            ],
        ),
    ]
