# Generated by Django 4.2.30 on 2026-05-14 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0002_remove_sample_location_id_sample_sample_name_and_more'),
        #('inventory', '0001_initial'),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Loaction',
            new_name='Location',
        ),
    ]
