# Generated by Django 4.2.30 on 2026-05-20 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_rename_loaction_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempLog',
            fields=[
                ('temp_log_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_logged', models.DateField()),
                ('current_temp_c', models.DecimalField(decimal_places=2, max_digits=5)),
                ('max_temp_c', models.DecimalField(decimal_places=2, max_digits=5)),
                ('min_temp_c', models.DecimalField(decimal_places=2, max_digits=5)),
                ('max_humidity', models.DecimalField(blank=True, decimal_places=2, help_text='Room locations only.', max_digits=5, null=True)),
                ('min_humidity', models.DecimalField(blank=True, decimal_places=2, help_text='Room locations only.', max_digits=5, null=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='templogs', to='locations.location')),
            ],
            options={
                'verbose_name': 'Temperature Log',
                'verbose_name_plural': 'Temperature Logs',
                'ordering': ['-date_logged'],
                'unique_together': {('location', 'date_logged')},
            },
        ),
        migrations.DeleteModel(
            name='Temp_Logs',
        ),
    ]
