# Generated by Django 4.2.30 on 2026-05-20 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_templog_delete_temp_logs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templog',
            name='date_logged',
            field=models.DateField(auto_now=True),
        ),
    ]
