# Generated by Django 4.2.30 on 2026-05-21 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_alter_templog_date_logged'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templog',
            name='date_logged',
            field=models.DateField(auto_now_add=True),
        ),
    ]
