# Generated by Django 4.2.30 on 2026-05-28 13:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('locations', '0005_alter_templog_date_logged'),
    ]

    operations = [
        migrations.AddField(
            model_name='templog',
            name='logged_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='temp_logs', to=settings.AUTH_USER_MODEL),
        ),
    ]
