# Generated by Django 4.2.30 on 2026-06-15 13:07

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('samples', '0014_userprofile'),
        ('locations', '0006_templog_logged_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rack_location', models.CharField(blank=True, help_text="Slot on the rack grid, e.g. 'A1', 'C3'.", max_length=4, validators=[django.core.validators.RegexValidator(message="Rack slot must be in the form 'A1' … 'D4'.", regex='^[A-D][1-4]$')])),
                ('plate_name', models.CharField(help_text="Plate barcode or human label, e.g. 'ACC-Mat-Batch-16-WGS-Lib-Prep-2-Kappa'.", max_length=160)),
                ('plate_format', models.CharField(choices=[('96', '96-well  (8 × 12)'), ('24', '24-well  (4 × 6)'), ('CUSTOM', 'Custom')], default='96', max_length=10)),
                ('custom_rows', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('custom_cols', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plates_created', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(help_text='Denormalised for fast location queries (mirrors Rack→Location).', on_delete=django.db.models.deletion.PROTECT, related_name='plates', to='locations.location')),
            ],
            options={
                'verbose_name': 'Plate',
                'verbose_name_plural': 'Plates',
                'ordering': ['rack', 'rack_location', 'plate_name'],
            },
        ),
        migrations.CreateModel(
            name='Rack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rack_name', models.CharField(help_text="e.g. 'Rack 1', 'Rack 2' …", max_length=80)),
                ('rows', models.PositiveSmallIntegerField(default=4, help_text='Number of rows (A … D by default).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(16)])),
                ('cols', models.PositiveSmallIntegerField(default=4, help_text='Number of columns (1 … 4 by default).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(24)])),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='racks_created', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='racks', to='locations.location')),
            ],
            options={
                'verbose_name': 'Rack',
                'verbose_name_plural': 'Racks',
                'ordering': ['location', 'rack_name'],
                'unique_together': {('location', 'rack_name')},
            },
        ),
        migrations.CreateModel(
            name='PlateLayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layout_name', models.CharField(default='Draft', help_text="e.g. 'Draft', 'Submitted', 'Committed'.", max_length=120)),
                ('is_committed', models.BooleanField(default=False, help_text='True once the layout has been written to PlateWell records.')),
                ('layout_data', models.JSONField(default=dict, help_text='Serialised well assignments from the drag-and-drop editor.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plate_layouts_created', to=settings.AUTH_USER_MODEL)),
                ('plate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layouts', to='locations.plate')),
            ],
            options={
                'verbose_name': 'Plate Layout',
                'verbose_name_plural': 'Plate Layouts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='plate',
            name='rack',
            field=models.ForeignKey(blank=True, help_text='Null if the plate is not yet placed on a rack.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='plates', to='locations.rack'),
        ),
        migrations.CreateModel(
            name='PlateWell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('well_position', models.CharField(help_text="Well address, e.g. 'A01', 'H12'.", max_length=4, validators=[django.core.validators.RegexValidator(message="Well position must be in the form 'A01' … 'H12'", regex='^[A-P](?:0[1-9]|1[0-9]|2[0-4]|[1-9])$')])),
                ('well_type', models.CharField(choices=[('sample', 'Sample'), ('library', 'Library Prep'), ('sequencing', 'Sequencing Batch'), ('control', 'Control'), ('empty', 'Empty')], default='empty', max_length=20)),
                ('volume_ul', models.FloatField(blank=True, help_text='Volume in µL loaded into the well.', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('concentration_nm', models.FloatField(blank=True, help_text='Concentration in nM (relevant for library prep wells).', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wells_created', to=settings.AUTH_USER_MODEL)),
                ('plate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wells', to='locations.plate')),
                ('sample', models.ForeignKey(blank=True, help_text='Set when this well holds a raw sample aliquot.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plate_wells', to='samples.sample')),
            ],
            options={
                'verbose_name': 'Plate Well',
                'verbose_name_plural': 'Plate Wells',
                'ordering': ['plate', 'well_position'],
                'unique_together': {('plate', 'well_position')},
            },
        ),
    ]
