# Generated by Django 4.2.30 on 2026-07-02 18:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0007_plate_rack_platelayout_plate_rack_platewell'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plate',
            name='rack_location',
            field=models.CharField(blank=True, help_text="Slot on the rack grid, e.g. 'A1', 'C3'.", max_length=4, validators=[django.core.validators.RegexValidator(message="Rack slot must be in the form 'A1', 'A1T', or 'A1B'.", regex='^[A-D][1-4][TB]?$')]),
        ),
    ]
