# Generated by Django 4.2.30 on 2026-08-07 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0008_alter_plate_rack_location'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='plate',
            constraint=models.UniqueConstraint(condition=models.Q(('rack_location', ''), _negated=True), fields=('rack', 'rack_location'), name='unique_occupied_rack_slot'),
        ),
    ]
