# Generated by Django 4.2.30 on 2026-05-13 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('case_id', models.AutoField(primary_key=True, serialize=False)),
                ('case_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('client_id', models.AutoField(primary_key=True, serialize=False)),
                ('client_name', models.CharField(max_length=255)),
                ('organisation_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.AutoField(primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=255)),
                ('sequencing_type', models.CharField(max_length=255)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='samples.client')),
            ],
        ),
        migrations.CreateModel(
            name='Specimen',
            fields=[
                ('specimen_id', models.AutoField(primary_key=True, serialize=False)),
                ('specimen_name', models.CharField(max_length=255)),
                ('specimen_origin', models.CharField(choices=[('Blood', 'Blood'), ('FFPE', 'FFPE'), ('Frozen Tissue', 'Frozen Tissue'), ('EV', 'EV')], max_length=255)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specimens', to='samples.case')),
            ],
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('sample_id', models.AutoField(primary_key=True, serialize=False)),
                ('location_id', models.IntegerField()),
                ('date_received', models.DateField()),
                ('volume_received', models.FloatField()),
                ('sample_type', models.CharField(choices=[('DNA', 'DNA'), ('RNA', 'RNA')], max_length=10)),
                ('receiving_condition', models.CharField(choices=[('Tubes', 'Tubes'), ('Plates', 'Plates'), ('Tube Strips', 'Tube Strips')], max_length=255)),
                ('parent_sample', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='re_extraction', to='samples.sample')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='samples', to='samples.project')),
                ('specimen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='samples', to='samples.specimen')),
            ],
        ),
        migrations.AddField(
            model_name='case',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cases', to='samples.client'),
        ),
    ]
