# Generated by Django 4.2.30 on 2026-05-13 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sample',
            name='location_id',
        ),
        migrations.AddField(
            model_name='sample',
            name='sample_name',
            field=models.CharField(default='ACC-PanCancer-FFPE-380-N-1-DNA-1', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='specimen',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='specimens', to='samples.case'),
        ),
    ]
