# Generated by Django 4.2.30 on 2026-05-14 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_rename_loaction_location'),
        ('samples', '0002_remove_sample_location_id_sample_sample_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='locations.location'),
        ),
    ]
