# Generated by Django 4.2.30 on 2026-05-20 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0003_sample_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecimenName',
            fields=[
                ('specimen_name', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AlterField(
            model_name='specimen',
            name='specimen_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='samples.specimenname'),
        ),
    ]
