# Generated by Django 4.2.30 on 2026-05-20 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0004_specimenname_alter_specimen_specimen_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sample',
            name='parent_sample',
        ),
        migrations.AlterField(
            model_name='sample',
            name='date_received',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='sample',
            name='volume_received',
            field=models.FloatField(null=True),
        ),
    ]
