# Generated by Django 4.2.30 on 2026-05-20 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0005_remove_sample_parent_sample_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specimen',
            name='specimen_origin',
        ),
    ]
