# Generated by Django 4.2.30 on 2026-05-21 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0006_remove_specimen_specimen_origin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='specimen',
            old_name='specimen_name',
            new_name='specimen_type',
        ),
        migrations.RenameField(
            model_name='specimenname',
            old_name='specimen_name',
            new_name='specimen_type',
        ),
    ]
