# Generated by Django 4.2.30 on 2026-05-21 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0007_rename_specimen_name_specimen_specimen_type_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SpecimenName',
            new_name='SpecimenType',
        ),
    ]
