# Generated by Django 4.2.30 on 2026-05-21 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0008_rename_specimenname_specimentype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='receiving_condition',
            field=models.CharField(blank=True, choices=[('Tubes', 'Tubes'), ('Plates', 'Plates'), ('Tube Strips', 'Tube Strips')], max_length=255),
        ),
        migrations.AlterField(
            model_name='sample',
            name='sample_name',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='sample',
            name='volume_received',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
