# Generated by Django 4.2.30 on 2026-05-25 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0009_alter_sample_receiving_condition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='compliance',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sample',
            name='notes',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
