# Generated by Django 4.2.30 on 2026-05-26 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0011_alter_project_project_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='concentration',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True),
        ),
    ]
