# Generated by Django 4.2.30 on 2026-05-27 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0012_sample_concentration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='concentration',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
