# Generated by Django 4.2.30 on 2026-06-23 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0014_userprofile'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='case',
            constraint=models.UniqueConstraint(fields=('client', 'case_name'), name='unique_case_per_client'),
        ),
        migrations.AddConstraint(
            model_name='specimen',
            constraint=models.UniqueConstraint(fields=('case', 'specimen_type'), name='unique_specimen_per_case'),
        ),
    ]
