# Generated by Django 4.2.30 on 2026-07-22 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0015_case_unique_case_per_client_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='contact_email',
            field=models.EmailField(blank=True, help_text='Optional contact email for this client.', max_length=255, null=True),
        ),
    ]
